"""One object tells MAX: *this is SmiTedModel — here's the tokenizer, batcher, graph, and weights.*"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_arch.ipynb.

# %% auto #0
__all__ = ['smi_ted_arch', 'ARCHITECTURES']

# %% ../nbs/06_arch.ipynb #d0231429
from max.graph.weights import WeightsFormat
from max.pipelines.context import TextContext
from max.pipelines.lib import SupportedArchitecture
from max.pipelines.modeling.types import PipelineTask

from . import weight_adapters
from .batch_processor import SmiTedBatchProcessor
from .model import SmiTedInputs, SmiTedPipelineModel
from .model_config import SmiTedModelConfig
from .tokenizer import SmiTedTokenizer


# %% ../nbs/06_arch.ipynb #63af9768
smi_ted_arch = SupportedArchitecture(
    name="SmiTedModel",
    task=PipelineTask.EMBEDDINGS_GENERATION,
    example_repo_ids=[
        "ibm-research/materials.smi-ted",
    ],
    default_encoding="float32",
    supported_encodings={
        "float32",
        "bfloat16",
    },
    pipeline_model=SmiTedPipelineModel,
    tokenizer=SmiTedTokenizer,
    context_type=TextContext,
    default_weights_format=WeightsFormat.safetensors,
    weight_adapters={
        WeightsFormat.safetensors: weight_adapters.convert_safetensor_state_dict,
    },
    required_arguments={"enable_prefix_caching": False},
    config=SmiTedModelConfig,
    batching=SmiTedBatchProcessor,
)


# %% ../nbs/06_arch.ipynb #3b3302ed
ARCHITECTURES = [smi_ted_arch]

