"""The network math: tokens ↔ 768-d molecular embedding (encode + decode)."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_graph.ipynb.

# %% ../nbs/03_graph.ipynb #b954322f
from __future__ import annotations

from collections.abc import Mapping

from max.driver import DLPackArray
from max.dtype import DType
from max.graph import DeviceRef, Graph, TensorType, TensorValue, Weight, ops
from max.graph.weights import WeightData
from max.nn.activation import activation_function_from_name
from max.nn.embedding import Embedding
from max.nn.layer import Module
from max.nn.sequential import Sequential
from max.nn.linear import Linear
from max.nn.norm import LayerNorm

from .model_config import SmiTedModelConfig


# %% auto #0
__all__ = ['FeatureMap', 'InnerLinearAttention', 'RotaryEmbedding', 'RotateAttentionLayer', 'TransformerEncoderLayer',
           'TransformerEncoderBlocks', 'MoLEncoder', 'AutoEncoderEncoder', 'AutoEncoderDecoder', 'AutoEncoder',
           'LangLayer', 'MoLDecoder', 'Net', 'SmiTedModel', 'build_graph', 'SmiTedDecodeModel', 'build_decode_graph']

# %% ../nbs/03_graph.ipynb #4db03ee2
def _reshape_heads(x: TensorValue, n_heads: int, head_dim: int) -> TensorValue:
    "Split the embedding dim into ``(n_heads, head_dim)``."
    batch, seq_len, _ = x.shape
    return ops.reshape(x, (batch, seq_len, n_heads, head_dim))


def _merge_heads(x: TensorValue, n_heads: int, head_dim: int) -> TensorValue:
    "Merge heads back into a single embedding dim."
    batch, seq_len, _, _ = x.shape
    return ops.reshape(x, (batch, seq_len, n_heads * head_dim))


# %% ../nbs/03_graph.ipynb #947ed3bd
def _rotate_half(x: TensorValue) -> TensorValue:
    "Rotate the last dim by swapping halves with a sign flip."
    head_dim = x.shape[-1]
    half = head_dim // 2
    x1, x2 = ops.split(x, [half, half], axis=-1)
    return ops.concat([-x2, x1], axis=-1)


def _apply_rotary_pos_emb(
    q: TensorValue, k: TensorValue, inv_freq: TensorValue
) -> tuple[TensorValue, TensorValue]:
    "Apply RoPE to queries and keys using a learned/loaded ``inv_freq``."
    seq_len = q.shape[1]
    device = q.device

    t = ops.range(0, seq_len, dtype=DType.float32, device=DeviceRef.CPU())
    t = t.to(device)
    freqs = ops.outer(t, inv_freq)
    emb = ops.concat([freqs, freqs], axis=-1)
    cos = ops.cos(emb)
    sin = ops.sin(emb)
    cos = ops.unsqueeze(ops.unsqueeze(cos, 0), 2)
    sin = ops.unsqueeze(ops.unsqueeze(sin, 0), 2)

    q_rot = (q * cos) + (_rotate_half(q) * sin)
    k_rot = (k * cos) + (_rotate_half(k) * sin)
    return q_rot, k_rot


# %% ../nbs/03_graph.ipynb #4e7b9a1d
class FeatureMap(Module):
    "ReLU generalized random features (Performer-style)."

    def __init__(self, head_dim: int, num_feats: int, device: DeviceRef) -> None:
        self.omega = Weight(
            "omega",
            DType.float32,
            [head_dim, num_feats],
            device=device,
        )

    def __call__(self, x: TensorValue) -> TensorValue:
        # x: [B, L, H, D]; omega: [D, M] — match HF `x @ omega` on the last dim.
        # Do not reshape to (B*H, L, D): that scrambles the head layout.
        return ops.relu(x @ self.omega)


# %% ../nbs/03_graph.ipynb #f7f85e4e
class InnerLinearAttention(Module):
    "Matches ``fast_transformers.attention.linear_attention.LinearAttention``."

    def __init__(self, head_dim: int, num_feats: int, device: DeviceRef, eps: float = 1e-6) -> None:
        self.eps = eps
        self.feature_map = FeatureMap(head_dim, num_feats, device)

    def __call__(
        self,
        queries: TensorValue,
        keys: TensorValue,
        values: TensorValue,
        length_mask: TensorValue,
    ) -> TensorValue:
        phi_q = self.feature_map(queries)
        phi_k = self.feature_map(keys)
        mask = ops.reshape(
            length_mask,
            (length_mask.shape[0], length_mask.shape[1], 1, 1),
        )
        phi_k = phi_k * mask
        values = values * mask

        # phi_k: [B, L, H, M], values: [B, L, H, D]
        # Match fast_transformers: KV = einsum("nshd,nshm->nhmd", K, V)
        phi_k_h = ops.permute(phi_k, [0, 2, 3, 1])  # [B, H, M, L]
        values_h = ops.permute(values, [0, 2, 1, 3])  # [B, H, L, D]
        kv = phi_k_h @ values_h  # [B, H, M, D]

        phi_q_h = ops.permute(phi_q, [0, 2, 1, 3])  # [B, H, L, M]
        out_h = phi_q_h @ kv  # [B, H, L, D]

        # Z = 1 / (einsum("nlhd,nhd->nlh", Q, K.sum(1)) + eps)
        # ops.sum keeps the reduced axis as size 1.
        k_sum = ops.sum(phi_k, axis=1)  # [B, 1, H, M]
        z_denom = ops.sum(phi_q * k_sum, axis=-1) + self.eps  # [B, L, H, 1]
        z = ops.div(1.0, z_denom)
        out = ops.permute(out_h, [0, 2, 1, 3])  # [B, L, H, D]
        return out * z


# %% ../nbs/03_graph.ipynb #1fbd797f
class RotaryEmbedding(Module):
    "Holds the RoPE ``inv_freq`` weight loaded from the checkpoint."

    def __init__(self, head_dim: int, device: DeviceRef) -> None:
        self.inv_freq = Weight(
            "inv_freq",
            DType.float32,
            [head_dim // 2],
            device=device,
        )

    def __call__(self, x: TensorValue) -> TensorValue:
        return x


# %% ../nbs/03_graph.ipynb #b282715c
class RotateAttentionLayer(Module):
    "QKV + RoPE + linear attention + output projection."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        self.n_heads = hf.n_head
        self.head_dim = hf.n_embd // hf.n_head
        inner_dim = self.n_heads * self.head_dim

        self.query_projection = Linear(
            hf.n_embd, inner_dim, dtype, device, has_bias=True
        )
        self.key_projection = Linear(
            hf.n_embd, inner_dim, dtype, device, has_bias=True
        )
        self.value_projection = Linear(
            hf.n_embd, inner_dim, dtype, device, has_bias=True
        )
        self.out_projection = Linear(
            inner_dim, hf.n_embd, dtype, device, has_bias=True
        )
        self.inner_attention = InnerLinearAttention(
            self.head_dim, hf.num_feats, device
        )
        self.rotaryemb = RotaryEmbedding(self.head_dim, device)

    def __call__(
        self, hidden_states: TensorValue, length_mask: TensorValue
    ) -> TensorValue:
        q = _reshape_heads(
            self.query_projection(hidden_states), self.n_heads, self.head_dim
        )
        k = _reshape_heads(
            self.key_projection(hidden_states), self.n_heads, self.head_dim
        )
        v = _reshape_heads(
            self.value_projection(hidden_states), self.n_heads, self.head_dim
        )
        q, k = _apply_rotary_pos_emb(q, k, self.rotaryemb.inv_freq)
        attn = self.inner_attention(q, k, v, length_mask)
        attn = _merge_heads(attn, self.n_heads, self.head_dim)
        return self.out_projection(attn)


# %% ../nbs/03_graph.ipynb #a4a3309d
class TransformerEncoderLayer(Module):
    "One encoder block: rotate-attn + FFN with fast_transformers norm order."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        self.attention = RotateAttentionLayer(config)
        self.linear1 = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.linear2 = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.norm1 = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )
        self.norm2 = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )

    def __call__(
        self, hidden_states: TensorValue, length_mask: TensorValue
    ) -> TensorValue:
        attn_out = self.attention(hidden_states, length_mask)
        # Match fast_transformers: y = x = norm1(x + attn); return norm2(x + ffn(y))
        hidden_states = self.norm1(hidden_states + attn_out)
        gelu = activation_function_from_name("gelu")
        y = gelu(self.linear1(hidden_states))
        y = self.linear2(y)
        return self.norm2(hidden_states + y)


# %% ../nbs/03_graph.ipynb #aeea5b9d
class TransformerEncoderBlocks(Module):
    "``n_layer`` encoder layers followed by a final LayerNorm."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        device = config.device
        self.layers = Sequential(
            [
                TransformerEncoderLayer(config)
                for _ in range(config.huggingface_config.n_layer)
            ]
        )
        self.norm = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )

    def __call__(
        self, hidden_states: TensorValue, length_mask: TensorValue
    ) -> TensorValue:
        for layer in self.layers.layers:
            hidden_states = layer(hidden_states, length_mask)
        return self.norm(hidden_states)


# %% ../nbs/03_graph.ipynb #918b2c7f
class MoLEncoder(Module):
    "Token embed + stacked rotate-attention encoder blocks."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        self.tok_emb = Embedding(hf.vocab_size, hf.n_embd, config.dtype, config.device)
        self.blocks = TransformerEncoderBlocks(config)

    def __call__(
        self, input_ids: TensorValue, length_mask: TensorValue
    ) -> TensorValue:
        x = self.tok_emb(input_ids)
        return self.blocks(x, length_mask)


# %% ../nbs/03_graph.ipynb #f5bd1808
class AutoEncoderEncoder(Module):
    "Flattened token states → 768-d latent (AE encoder)."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        feature_size = hf.max_len * hf.n_embd
        self.fc1 = Linear(feature_size, hf.n_embd, dtype, device, has_bias=True)
        self.ln_f = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )
        self.lat = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=False)

    def __call__(self, flat_tokens: TensorValue) -> TensorValue:
        gelu = activation_function_from_name("gelu")
        x = gelu(self.fc1(flat_tokens))
        x = self.ln_f(x)
        return self.lat(x)


class AutoEncoderDecoder(Module):
    "768-d latent → flattened token embeddings (AE decoder)."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        feature_size = hf.max_len * hf.n_embd
        self.fc1 = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.ln_f = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )
        self.rec = Linear(hf.n_embd, feature_size, dtype, device, has_bias=False)

    def __call__(self, latent: TensorValue) -> TensorValue:
        gelu = activation_function_from_name("gelu")
        x = gelu(self.fc1(latent))
        x = self.ln_f(x)
        return self.rec(x)


class AutoEncoder(Module):
    "Thin wrapper matching the Hub ``decoder.autoencoder`` nesting."

    def __init__(self, config: SmiTedModelConfig) -> None:
        self.encoder = AutoEncoderEncoder(config)
        self.decoder = AutoEncoderDecoder(config)

    def __call__(self, x: TensorValue) -> TensorValue:
        return self.encoder(x)


class LangLayer(Module):
    "Token embeddings → vocab logits (IBM ``decoder.lang_model``)."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        self.embed = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.ln_f = LayerNorm(
            hf.n_embd, devices=[device], dtype=DType.float32, eps=1e-5, use_bias=True
        )
        self.head = Linear(hf.n_embd, hf.vocab_size, dtype, device, has_bias=False)

    def __call__(self, token_embeddings: TensorValue) -> TensorValue:
        gelu = activation_function_from_name("gelu")
        x = gelu(self.embed(token_embeddings))
        x = self.ln_f(x)
        return self.head(x)


class MoLDecoder(Module):
    "AE encode/decode + lang head (encode path uses AE encoder only)."

    def __init__(self, config: SmiTedModelConfig) -> None:
        self.autoencoder = AutoEncoder(config)
        self.lang_model = LangLayer(config)

    def __call__(self, x: TensorValue) -> TensorValue:
        return self.autoencoder.encoder(x)


# %% ../nbs/03_graph.ipynb #21365fbe
class Net(Module):
    "IBM SMI-TED property head (inference: no dropout)."

    def __init__(self, config: SmiTedModelConfig) -> None:
        hf = config.huggingface_config
        dtype = config.dtype
        device = config.device
        self.fc1 = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.fc2 = Linear(hf.n_embd, hf.n_embd, dtype, device, has_bias=True)
        self.final = Linear(hf.n_embd, hf.n_output, dtype, device, has_bias=True)

    def __call__(self, embeddings: TensorValue) -> TensorValue:
        gelu = activation_function_from_name("gelu")
        x_out = gelu(self.fc1(embeddings))
        x_out = x_out + embeddings
        z = gelu(self.fc2(x_out))
        return self.final(z + x_out)


class SmiTedModel(Module):
    "SMI-TED encode graph: SMILES → embedding, optionally → property."

    def __init__(self, config: SmiTedModelConfig) -> None:
        self.config = config
        self.encoder = MoLEncoder(config)
        self.decoder = MoLDecoder(config)
        self.net = Net(config)

    def __call__(
        self, input_ids: TensorValue, attention_mask: TensorValue
    ) -> TensorValue:
        hf = self.config.huggingface_config
        token_embeddings = self.encoder(input_ids, attention_mask)

        mask_expanded = ops.broadcast_to(
            ops.unsqueeze(attention_mask, -1),
            (token_embeddings.shape[0], token_embeddings.shape[1], hf.n_embd),
        )
        masked = token_embeddings * mask_expanded
        flat = ops.reshape(masked, (masked.shape[0], hf.max_len * hf.n_embd))
        embedding = self.decoder.autoencoder.encoder(flat)
        if hf.is_property_output:
            return self.net(embedding)
        return embedding


# %% ../nbs/03_graph.ipynb #86c65063
def build_graph(
    config: SmiTedModelConfig,
    state_dict: Mapping[str, DLPackArray | WeightData],
) -> Graph:
    "Build the MAX ``Graph`` for SMI-TED encode (and optional property head)."
    max_len = config.huggingface_config.max_len
    input_ids_type = TensorType(
        DType.int64, shape=["batch_size", max_len], device=config.device
    )
    attention_mask_type = TensorType(
        DType.float32, shape=["batch_size", max_len], device=config.device
    )

    # Embedding serve still constructs ``Net`` so ``net.*`` keys from Hub
    # safetensors load cleanly; they are unused when not in property mode.
    with Graph(
        "smi_ted", input_types=[input_ids_type, attention_mask_type]
    ) as graph:
        model = SmiTedModel(config)
        model.load_state_dict(state_dict)
        input_ids = graph.inputs[0].tensor
        attention_mask = graph.inputs[1].tensor
        graph.output(model(input_ids, attention_mask))

    return graph


# %% ../nbs/03_graph.ipynb #2d7d8c6d
class SmiTedDecodeModel(Module):
    "SMI-TED decode graph: 768-d embedding → token ids."

    def __init__(self, config: SmiTedModelConfig) -> None:
        self.config = config
        self.decoder = MoLDecoder(config)

    def __call__(self, embeddings: TensorValue) -> TensorValue:
        hf = self.config.huggingface_config
        flat = self.decoder.autoencoder.decoder(embeddings)
        token_embeddings = ops.reshape(
            flat, (embeddings.shape[0], hf.max_len, hf.n_embd)
        )
        logits = self.decoder.lang_model(token_embeddings)
        # MAX ``argmax`` keeps a size-1 axis; squeeze to ``[batch, max_len]``.
        return ops.squeeze(ops.argmax(logits, axis=-1), -1)


def build_decode_graph(
    config: SmiTedModelConfig,
    state_dict: Mapping[str, DLPackArray | WeightData],
) -> Graph:
    "Build the MAX ``Graph`` for SMI-TED decode (embedding → token ids)."
    n_embd = config.huggingface_config.n_embd
    embedding_type = TensorType(
        DType.float32, shape=["batch_size", n_embd], device=config.device
    )
    decode_state = {
        key: value
        for key, value in state_dict.items()
        if key.startswith("decoder.")
    }
    with Graph("smi_ted_decode", input_types=[embedding_type]) as graph:
        model = SmiTedDecodeModel(config)
        model.load_state_dict(decode_state)
        embeddings = graph.inputs[0].tensor
        graph.output(model(embeddings))

    return graph

