"""Pull the handful of HuggingFace fields SMI-TED actually needs, then wrap them for MAX.

Docs: https://alix559.github.io/mat-gram01/config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% ../nbs/00_config.ipynb #107fbff1
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from max.dtype import DType
from max.graph import DeviceRef
from max.pipelines.lib import MAXModelConfig, PipelineConfig
from max.pipelines.lib.interfaces.arch_config import (
    ArchConfig,
    ArchConfigWithBoundedMaxSeqLen,
)
from max.pipelines.modeling.config_enums import supported_encoding_dtype
from typing_extensions import Self, override


# %% auto #0
__all__ = ['SmiTedHFConfig', 'SmiTedModelConfig']

# %% ../nbs/00_config.ipynb #fb61b8f8
@dataclass
class SmiTedHFConfig:
    "Subset of Hub ``config.json`` fields used by the MAX graph."
    model_type: str = "SMI-TED"
    architectures: list[str] | None = None
    n_layer: int = 12
    n_head: int = 12
    n_embd: int = 768
    max_len: int = 202
    num_feats: int = 32
    d_dropout: float = 0.1
    vocab_size: int = 2393

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> SmiTedHFConfig:
        "Build from a raw HuggingFace config dict (or ``to_dict()`` output)."
        return cls(
            model_type=data.get("model_type", "SMI-TED"),
            architectures=data.get("architectures"),
            n_layer=int(data.get("n_layer", 12)),
            n_head=int(data.get("n_head", 12)),
            n_embd=int(data.get("n_embd", 768)),
            max_len=int(data.get("max_len", 202)),
            num_feats=int(data.get("num_feats", 32)),
            d_dropout=float(data.get("d_dropout", 0.1)),
            vocab_size=int(data.get("vocab_size", 2393)),
        )


# %% ../nbs/00_config.ipynb #ab80595b
@dataclass(kw_only=True)
class SmiTedModelConfig(ArchConfigWithBoundedMaxSeqLen, ArchConfig):
    "MAX architecture config: dtype, device, HF hyperparams, bounded seq len."
    dtype: DType
    device: DeviceRef
    huggingface_config: SmiTedHFConfig
    max_seq_len: int

    @override
    @classmethod
    def initialize(
        cls,
        pipeline_config: PipelineConfig,
        model_config: MAXModelConfig | None = None,
    ) -> Self:
        model_config = model_config or pipeline_config.model
        quantization_encoding = model_config.quantization_encoding
        if quantization_encoding is None:
            raise ValueError("quantization_encoding must not be None")
        if len(model_config.device_specs) != 1:
            raise ValueError("SMI-TED is only supported on a single device")

        device_spec = model_config.device_specs[0]
        raw = model_config.huggingface_config
        if raw is None:
            raise ValueError(
                "HuggingFace config is required for SMI-TED. "
                "Use the patched config under max_ports/model_assets/."
            )

        if hasattr(raw, "to_dict"):
            hf_dict = raw.to_dict()
        elif isinstance(raw, dict):
            hf_dict = raw
        else:
            hf_dict = {
                key: getattr(raw, key)
                for key in (
                    "model_type",
                    "architectures",
                    "n_layer",
                    "n_head",
                    "n_embd",
                    "max_len",
                    "num_feats",
                    "d_dropout",
                    "vocab_size",
                )
                if hasattr(raw, key)
            }

        huggingface_config = SmiTedHFConfig.from_dict(hf_dict)
        if huggingface_config.vocab_size <= 0:
            huggingface_config.vocab_size = 2393

        return cls(
            dtype=supported_encoding_dtype(quantization_encoding),
            device=DeviceRef(
                device_type=device_spec.device_type, id=device_spec.id
            ),
            huggingface_config=huggingface_config,
            max_seq_len=huggingface_config.max_len,
        )

