"""Keep encode-path tensors (and optional `net.*` for property serve); drop LM / AE-decoder heads."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_weights.ipynb.

# %% ../nbs/02_weights.ipynb #cf1207f5
from __future__ import annotations

from collections.abc import Mapping

from max.graph.weights import WeightData, Weights


# %% auto #0
__all__ = ['convert_safetensor_state_dict']

# %% ../nbs/02_weights.ipynb #f403e635
# Training-only heads not used by the encode / property graphs.
_IGNORE_PREFIXES = (
    "encoder.lang_model.",
    "decoder.lang_model.",
    "decoder.autoencoder.decoder.",
)


# %% ../nbs/02_weights.ipynb #39824f8a
def convert_safetensor_state_dict(
    state_dict: Mapping[str, Weights],
) -> dict[str, WeightData]:
    "Filter Hub / finetune safetensors for the encode + optional ``net`` graph."
    new_state_dict: dict[str, WeightData] = {}

    for weight_name, value in state_dict.items():
        if any(weight_name.startswith(prefix) for prefix in _IGNORE_PREFIXES):
            continue
        if not (
            weight_name.startswith("encoder.")
            or weight_name.startswith("decoder.autoencoder.encoder.")
            or weight_name.startswith("net.")
        ):
            continue
        if value is None:
            continue
        new_state_dict[weight_name] = value.data()

    return new_state_dict

