"""Keep only the tensors the encode graph needs; drop LM and property heads.

Docs: https://alix559.github.io/mat-gram01/weights.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_weights.ipynb.

# %% ../nbs/02_weights.ipynb #7f7426ed
from __future__ import annotations

from collections.abc import Mapping

from max.graph.weights import WeightData, Weights


# %% auto #0
__all__ = ['convert_safetensor_state_dict']

# %% ../nbs/02_weights.ipynb #de1ea579
# Training-only / downstream heads not used by the encode graph.
_IGNORE_PREFIXES = (
    "encoder.lang_model.",
    "decoder.lang_model.",
    "decoder.autoencoder.decoder.",
    "net.",
)


# %% ../nbs/02_weights.ipynb #b1536d7d
def convert_safetensor_state_dict(
    state_dict: Mapping[str, Weights],
) -> dict[str, WeightData]:
    "Filter Hub safetensors down to encode-graph weights."
    new_state_dict: dict[str, WeightData] = {}

    for weight_name, value in state_dict.items():
        if any(weight_name.startswith(prefix) for prefix in _IGNORE_PREFIXES):
            continue
        if not (
            weight_name.startswith("encoder.")
            or weight_name.startswith("decoder.autoencoder.encoder.")
        ):
            continue
        if value is None:
            continue
        new_state_dict[weight_name] = value.data()

    return new_state_dict

